### ISSUE TITLE
hscript code block overrided by native one ?

### ISSUE THREAD

**Issue by tpr-evilempire** [jeremyfa/interpret#5] opened 2019-10-30 16:24 UTC
Hello there,
being satisfied with my test on hashlink platform with that excellent lib, I gave it a try over our production project. (which is a game).

I manage to make soemthing apparently working.  At first, I didn't catch the #if interpretABLE  token and used #interpret , and on haxe 4 version I had to come up with some hacks to make the __interpretWatch static  actually being called. (var watch = __interpretWatch; does the trick).
https://try.haxe.org/#fc965

So now I have the file changes detected, and getting some wierd result/behaviour. And I hope you can help me finding whats is happening here .

Here the code I'm "interpreting" on my game entity : 
```
override function postUpdate() {
	super.postUpdate();
	behave();
}
@interpret function behave() {
	trace("Behave");
}
````

Let say, the game run and prints "Behave" every frame correctly.
If I'm changing that text to something like "Behave from interpreter" like so : 

```
@interpret function behave() {
	trace("Behave from interpreter");
}
```

I'll get in game output (which is a trace redirection) : 
```
my.entity.Boss(lineNumber): Behave
interpret/macros/InterpretableMacro.hx:322: File changed at path myEntityFilePath.hx
hscript:9: Behave from interpreter
my.entity.Boss(lineNumber): Behave
my.entity.Boss(lineNumber): Behave
my.entity.Boss(lineNumber): Behave
my.entity.Boss(lineNumber): Behave
...
```

everytime I make a change, I'm getting the desired print change, but not the frames after that, that will be the native text ..

Any idea on what is happening here? 
(I do have other question after that one, which might be related, so let see if solving this one resolves the other first :) )

**Comment by tpr-evilempire** [comment] 2019-10-30 16:27
in fact, I do have a stack of error.

Note : my code above wasn't the full one I'm using, I do have some gameplay code right after the trace (which displays... so the problem weems to be related to the rest of the code.  MAybe hscript adaptation of haxe code  isn't complete?)
```
...
interpret.Interpreter.get (interpret/Interpreter.hx)
hscript.Interp.get (hscript/Interp.hx)
[error] hscript:10: Invalid access to field width
```

Field access is : 
``` 
spr.tile.width
```
with : 
var spr: HSprite;
HSprite.hx: 
public var tile(get,never) : Tile;
inline function get_tile() {
....
}
Tile.hx
public var width(default,null) : Int;

**Comment by tpr-evilempire** [comment] 2019-10-31 09:21
Ok, more progress on this. In fact I manage to get it working.

In the gameplay code, I had something which isn't interpretable (or converted to hscript).  I also had to remove inlining.
Once those 2 conditions found and fixed, it does work and that's really really nice !

Now following questions :
- is it possible to register all the module from a package directly ?  (DynamicPackage?)
- haxe you considered to automatically add to Env the classes implementing Interpretable ?
- How could I help the library development ?

Regards,

**Comment by jeremyfa** [comment] 2019-10-31 11:30
Glad you found a solution!

Yes, there are many things that are not handled with interpret. The unit tests in the library can help to see what works / what doesn't work. In practice, it should work well with classes with non-inlined methods and primitive types. Abstract kind of work but still have limitation and are a bit experimental.

The `Env` class is a way to create reproducible and contained environments no matter what the project becomes. Adding automatically classes to `Env` would defeat this purpose: if you had multiple `Env` instances, you would be forced to have every interpretable classes in it, which is not always wanted.

I didn't find a way to register all modules from a package at the moment. I guess that would be possible by improving the related macro, but did not work on this.

You can definitely help if you want to add features. Just ensure that the existing tests are still passing, and beware that the code in this project is pretty hairy :P

**Comment by kiroukou** [comment] 2019-11-04 08:14
Ok, You could close this issue, since it was related to an error while generating the interpretable counterpart of the code (macro stuff plus inlined code...)

**Closed as completed** 2019-11-04 09:02 UTC
